//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.05 at 03:21:47 PM CEST 
//


package it.polito.dp2.NFV.sol3.service.model.nfvdeployer;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NfvLink complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NfvLink">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="sourceNode" type="{http://www.example.org/NfvDeployer}NfvNode"/>
 *             &lt;element name="destinationNode" type="{http://www.example.org/NfvDeployer}NfvNode"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="sourceHost" type="{http://www.example.org/NfvDeployer}NfvHost"/>
 *             &lt;element name="destinationHost" type="{http://www.example.org/NfvDeployer}NfvHost"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="minThroughput" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="maxLatency" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NfvLink", propOrder = {
    "name",
    "sourceNode",
    "destinationNode",
    "sourceHost",
    "destinationHost",
    "minThroughput",
    "maxLatency"
})
public class NfvLink {

    @XmlElement(required = true)
    protected String name;
    protected NfvNode sourceNode;
    protected NfvNode destinationNode;
    protected NfvHost sourceHost;
    protected NfvHost destinationHost;
    protected Float minThroughput;
    protected BigInteger maxLatency;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the sourceNode property.
     * 
     * @return
     *     possible object is
     *     {@link NfvNode }
     *     
     */
    public NfvNode getSourceNode() {
        return sourceNode;
    }

    /**
     * Sets the value of the sourceNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link NfvNode }
     *     
     */
    public void setSourceNode(NfvNode value) {
        this.sourceNode = value;
    }

    /**
     * Gets the value of the destinationNode property.
     * 
     * @return
     *     possible object is
     *     {@link NfvNode }
     *     
     */
    public NfvNode getDestinationNode() {
        return destinationNode;
    }

    /**
     * Sets the value of the destinationNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link NfvNode }
     *     
     */
    public void setDestinationNode(NfvNode value) {
        this.destinationNode = value;
    }

    /**
     * Gets the value of the sourceHost property.
     * 
     * @return
     *     possible object is
     *     {@link NfvHost }
     *     
     */
    public NfvHost getSourceHost() {
        return sourceHost;
    }

    /**
     * Sets the value of the sourceHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link NfvHost }
     *     
     */
    public void setSourceHost(NfvHost value) {
        this.sourceHost = value;
    }

    /**
     * Gets the value of the destinationHost property.
     * 
     * @return
     *     possible object is
     *     {@link NfvHost }
     *     
     */
    public NfvHost getDestinationHost() {
        return destinationHost;
    }

    /**
     * Sets the value of the destinationHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link NfvHost }
     *     
     */
    public void setDestinationHost(NfvHost value) {
        this.destinationHost = value;
    }

    /**
     * Gets the value of the minThroughput property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMinThroughput() {
        return minThroughput;
    }

    /**
     * Sets the value of the minThroughput property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMinThroughput(Float value) {
        this.minThroughput = value;
    }

    /**
     * Gets the value of the maxLatency property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxLatency() {
        return maxLatency;
    }

    /**
     * Sets the value of the maxLatency property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxLatency(BigInteger value) {
        this.maxLatency = value;
    }

}
