//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.05 at 03:21:47 PM CEST 
//


package it.polito.dp2.NFV.sol3.service.model.nfvdeployer;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polito.dp2.NFV.sol3.service.model.nfvdeployer package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Nodes_QNAME = new QName("http://www.example.org/NfvDeployer", "nodes");
    private final static QName _Node_QNAME = new QName("http://www.example.org/NfvDeployer", "node");
    private final static QName _Hosts_QNAME = new QName("http://www.example.org/NfvDeployer", "hosts");
    private final static QName _Nffgs_QNAME = new QName("http://www.example.org/NfvDeployer", "nffgs");
    private final static QName _Nffg_QNAME = new QName("http://www.example.org/NfvDeployer", "nffg");
    private final static QName _Links_QNAME = new QName("http://www.example.org/NfvDeployer", "links");
    private final static QName _Host_QNAME = new QName("http://www.example.org/NfvDeployer", "host");
    private final static QName _Link_QNAME = new QName("http://www.example.org/NfvDeployer", "link");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polito.dp2.NFV.sol3.service.model.nfvdeployer
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NfvNode }
     * 
     */
    public NfvNode createNfvNode() {
        return new NfvNode();
    }

    /**
     * Create an instance of {@link NfvNodes }
     * 
     */
    public NfvNodes createNfvNodes() {
        return new NfvNodes();
    }

    /**
     * Create an instance of {@link NfvNFFGs }
     * 
     */
    public NfvNFFGs createNfvNFFGs() {
        return new NfvNFFGs();
    }

    /**
     * Create an instance of {@link NfvHosts }
     * 
     */
    public NfvHosts createNfvHosts() {
        return new NfvHosts();
    }

    /**
     * Create an instance of {@link NfvHost }
     * 
     */
    public NfvHost createNfvHost() {
        return new NfvHost();
    }

    /**
     * Create an instance of {@link NfvLink }
     * 
     */
    public NfvLink createNfvLink() {
        return new NfvLink();
    }

    /**
     * Create an instance of {@link NfvNFFG }
     * 
     */
    public NfvNFFG createNfvNFFG() {
        return new NfvNFFG();
    }

    /**
     * Create an instance of {@link NfvLinks }
     * 
     */
    public NfvLinks createNfvLinks() {
        return new NfvLinks();
    }

    /**
     * Create an instance of {@link SelfRef }
     * 
     */
    public SelfRef createSelfRef() {
        return new SelfRef();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NfvNodes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/NfvDeployer", name = "nodes")
    public JAXBElement<NfvNodes> createNodes(NfvNodes value) {
        return new JAXBElement<NfvNodes>(_Nodes_QNAME, NfvNodes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NfvNode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/NfvDeployer", name = "node")
    public JAXBElement<NfvNode> createNode(NfvNode value) {
        return new JAXBElement<NfvNode>(_Node_QNAME, NfvNode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NfvHosts }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/NfvDeployer", name = "hosts")
    public JAXBElement<NfvHosts> createHosts(NfvHosts value) {
        return new JAXBElement<NfvHosts>(_Hosts_QNAME, NfvHosts.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NfvNFFGs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/NfvDeployer", name = "nffgs")
    public JAXBElement<NfvNFFGs> createNffgs(NfvNFFGs value) {
        return new JAXBElement<NfvNFFGs>(_Nffgs_QNAME, NfvNFFGs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NfvNFFG }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/NfvDeployer", name = "nffg")
    public JAXBElement<NfvNFFG> createNffg(NfvNFFG value) {
        return new JAXBElement<NfvNFFG>(_Nffg_QNAME, NfvNFFG.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NfvLinks }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/NfvDeployer", name = "links")
    public JAXBElement<NfvLinks> createLinks(NfvLinks value) {
        return new JAXBElement<NfvLinks>(_Links_QNAME, NfvLinks.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NfvHost }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/NfvDeployer", name = "host")
    public JAXBElement<NfvHost> createHost(NfvHost value) {
        return new JAXBElement<NfvHost>(_Host_QNAME, NfvHost.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NfvLink }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/NfvDeployer", name = "link")
    public JAXBElement<NfvLink> createLink(NfvLink value) {
        return new JAXBElement<NfvLink>(_Link_QNAME, NfvLink.class, null, value);
    }

}
