//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.27 at 11:25:44 PM CEST 
//


package it.polito.dp2.NFV.sol3.client1.model.nfvdeployer;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polito.dp2.NFV.sol3.client1.model.nfvdeployer package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polito.dp2.NFV.sol3.client1.model.nfvdeployer
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NfvVNFs }
     * 
     */
    public NfvVNFs createNfvVNFs() {
        return new NfvVNFs();
    }

    /**
     * Create an instance of {@link NfvVNF }
     * 
     */
    public NfvVNF createNfvVNF() {
        return new NfvVNF();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link NfvNodes }
     * 
     */
    public NfvNodes createNfvNodes() {
        return new NfvNodes();
    }

    /**
     * Create an instance of {@link NfvNode }
     * 
     */
    public NfvNode createNfvNode() {
        return new NfvNode();
    }

    /**
     * Create an instance of {@link NfvArc }
     * 
     */
    public NfvArc createNfvArc() {
        return new NfvArc();
    }

    /**
     * Create an instance of {@link NfvArcs }
     * 
     */
    public NfvArcs createNfvArcs() {
        return new NfvArcs();
    }

    /**
     * Create an instance of {@link NfvNFFG }
     * 
     */
    public NfvNFFG createNfvNFFG() {
        return new NfvNFFG();
    }

    /**
     * Create an instance of {@link NfvNFFGs }
     * 
     */
    public NfvNFFGs createNfvNFFGs() {
        return new NfvNFFGs();
    }

    /**
     * Create an instance of {@link NfvHost }
     * 
     */
    public NfvHost createNfvHost() {
        return new NfvHost();
    }

    /**
     * Create an instance of {@link Services }
     * 
     */
    public Services createServices() {
        return new Services();
    }

    /**
     * Create an instance of {@link NfvHosts }
     * 
     */
    public NfvHosts createNfvHosts() {
        return new NfvHosts();
    }

}
