//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.27 at 11:25:45 PM CEST 
//


package it.polito.dp2.NFV.sol3.client2.model.nfvdeployer;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="functionalType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hostingHost" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="associatedNFFG" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.example.org/NfvDeployer}nfvArc" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="self" type="{http://www.example.org/NfvDeployer}Link" minOccurs="0"/>
 *         &lt;element name="functionalTypeLink" type="{http://www.example.org/NfvDeployer}Link" minOccurs="0"/>
 *         &lt;element name="hostingHostLink" type="{http://www.example.org/NfvDeployer}Link" minOccurs="0"/>
 *         &lt;element name="associatedNFFGLink" type="{http://www.example.org/NfvDeployer}Link" minOccurs="0"/>
 *         &lt;element name="linksLink" type="{http://www.example.org/NfvDeployer}Link" minOccurs="0"/>
 *         &lt;element name="reachableHostsLink" type="{http://www.example.org/NfvDeployer}Link" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "functionalType",
    "hostingHost",
    "associatedNFFG",
    "nfvArc",
    "self",
    "functionalTypeLink",
    "hostingHostLink",
    "associatedNFFGLink",
    "linksLink",
    "reachableHostsLink"
})
@XmlRootElement(name = "nfvNode")
public class NfvNode {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String functionalType;
    protected String hostingHost;
    @XmlElement(required = true)
    protected String associatedNFFG;
    protected List<NfvArc> nfvArc;
    protected Link self;
    protected Link functionalTypeLink;
    protected Link hostingHostLink;
    protected Link associatedNFFGLink;
    protected Link linksLink;
    protected Link reachableHostsLink;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the functionalType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunctionalType() {
        return functionalType;
    }

    /**
     * Sets the value of the functionalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunctionalType(String value) {
        this.functionalType = value;
    }

    /**
     * Gets the value of the hostingHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostingHost() {
        return hostingHost;
    }

    /**
     * Sets the value of the hostingHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostingHost(String value) {
        this.hostingHost = value;
    }

    /**
     * Gets the value of the associatedNFFG property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssociatedNFFG() {
        return associatedNFFG;
    }

    /**
     * Sets the value of the associatedNFFG property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssociatedNFFG(String value) {
        this.associatedNFFG = value;
    }

    /**
     * Gets the value of the nfvArc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nfvArc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNfvArc().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NfvArc }
     * 
     * 
     */
    public List<NfvArc> getNfvArc() {
        if (nfvArc == null) {
            nfvArc = new ArrayList<NfvArc>();
        }
        return this.nfvArc;
    }

    /**
     * Gets the value of the self property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public Link getSelf() {
        return self;
    }

    /**
     * Sets the value of the self property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setSelf(Link value) {
        this.self = value;
    }

    /**
     * Gets the value of the functionalTypeLink property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public Link getFunctionalTypeLink() {
        return functionalTypeLink;
    }

    /**
     * Sets the value of the functionalTypeLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setFunctionalTypeLink(Link value) {
        this.functionalTypeLink = value;
    }

    /**
     * Gets the value of the hostingHostLink property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public Link getHostingHostLink() {
        return hostingHostLink;
    }

    /**
     * Sets the value of the hostingHostLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setHostingHostLink(Link value) {
        this.hostingHostLink = value;
    }

    /**
     * Gets the value of the associatedNFFGLink property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public Link getAssociatedNFFGLink() {
        return associatedNFFGLink;
    }

    /**
     * Sets the value of the associatedNFFGLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setAssociatedNFFGLink(Link value) {
        this.associatedNFFGLink = value;
    }

    /**
     * Gets the value of the linksLink property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public Link getLinksLink() {
        return linksLink;
    }

    /**
     * Sets the value of the linksLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setLinksLink(Link value) {
        this.linksLink = value;
    }

    /**
     * Gets the value of the reachableHostsLink property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public Link getReachableHostsLink() {
        return reachableHostsLink;
    }

    /**
     * Sets the value of the reachableHostsLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setReachableHostsLink(Link value) {
        this.reachableHostsLink = value;
    }

}
